### ISSUE TITLE
dor.html | Advanced checkbox system

### ISSUE THREAD

**Issue by pepper-forms** [pepper-forms/pepper-forms.github.io#19]
![image](https://user-images.githubusercontent.com/50184364/57589130-0dab9100-7528-11e9-9c2c-1b3e68805618.png)

Possibly, make the system like this.

![image](https://user-images.githubusercontent.com/50184364/57589125-03899280-7528-11e9-8aca-4135cc4d9e1a.png)

So, this group of 5 columns (N/O | NRT | [N/I | C | S]) (in that order) must be RADIOS (user can pick only 1 option).

![image](https://user-images.githubusercontent.com/50184364/57589221-b7d7e880-7529-11e9-9880-bcb1cac10b87.png)

This one must be checkbox.

SOMEHOW LINK IT WITH BBCODE, SO FINAL RESULT WOULD BE:

TEXT: N/I, DS

**Comment by ArtemyMagarin** [comment]
Funny meme, scary situation

**Comment by pepper-forms** [comment]
realized
