### ISSUE TITLE
We need dropdown box to fill the span

### ISSUE THREAD

**Issue by pepper-forms** [pepper-forms/pepper-forms.github.io#3]
![image](https://user-images.githubusercontent.com/50184364/57262528-24a83a00-7075-11e9-83c5-fa822fe87712.png)

**Comment by ArtemyMagarin** [comment]
Do we really need dropdowns? 🤔🤔🤔

**Comment by ArtemyMagarin** [comment]
OK, will do 🙄

**Comment by pepper-forms** [comment]
Added "put select here" mark on places, that needs dropdown menu.
